version: 2.1

jobs:
  prebuilt:
    docker:
      - image: circleci/node:12.15.0
    steps:
      - checkout
      - run: npm i msnodesqlv8@0.8.14

  buildyourown:
    docker:
      - image: circleci/node:12.15.0
    steps:
      - checkout
      - run: npm i msnodesqlv8@1.1.0

workflows:
  version: 2

  test:
    jobs:
      - prebuilt
      - buildyourown
